### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [LayoutXML/AppListManager#3]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by LayoutXML** [comment]
Hi mansya,

This project is actually an android library that anyone can use in their projects, not a standalone project itself. There is however a sample app included (/app folder) but it doesn't serve any purpose. Unless you really want to make a logo for it I don't think it would be a good use of your time. What do you think?

**Comment by mansya** [comment]
I have designed the logo for this project. What do you think ? do you like it ? if yes let me know and if there are changes please let me know.
![portofolio](https://user-images.githubusercontent.com/33461607/48613280-dc5d6880-e9bd-11e8-8cb5-31bc0e71787c.png)

**Comment by LayoutXML** [comment]
Hi, I like the bottom left one. I would remove spaces though because the name is supposed to be 1 word

**Comment by mansya** [comment]
I changed it according to your request. and I have also sent you [**Pull Requests**](https://github.com/LayoutXML/AppListManager/pull/4). please check. and for all the files I have also uploaded to this [**Drive.**](https://drive.google.com/open?id=11kM_8qyh4n2Gd3H3Hj_8ylkfUlWIufXp)

**Comment by LayoutXML** [comment]
Thank you.

**Comment by LayoutXML** [comment]
Hi, I have changed the logo a little bit for the Android app and temporarily removed it from the readme page because github is not showing me any pictures there at all - I will add it back after I investigate further. Hope you don't mind.

**Comment by LayoutXML** [comment]
I don't know why it's not showing for me. At first I though it was because of the relative path but I've tried changing that, saving the logo as png, even editing and saving from a screenshot it still not showing up for me unless I visit this repository on IE. It's not working on chrome.
